BUILD_FINGERPRINT=samsung/gta4xlwifixx/gta4xlwifi:13/TP1A.220624.014/P610XXS6FXJ1:user/release-keys
BUILD_DESCRIPTION=gta4xlwifixx-user 13 TP1A.220624.014 P610XXS6FXJ1 release-keys
BUILD_SECURITY_PATCH_DATE=2024-11-01
BUILD_TAGS=release-keys
BUILD_TYPE=user
BUILD_VERSION_RELEASE=13
DEBUGGABLE=0
