BUILD_FINGERPRINT=samsung/gta4xlxx/gta4xl:13/TP1A.220624.014/P615XXSAFYD1:user/release-keys
BUILD_DESCRIPTION=gta4xlxx-user 13 TP1A.220624.014 P615XXSAFYD1 release-keys
BUILD_SECURITY_PATCH_DATE=2025-04-01
BUILD_TAGS=release-keys
BUILD_TYPE=user
BUILD_VERSION_RELEASE=13
DEBUGGABLE=0
